### PR TITLE
Support year in date formatting

### PR DESCRIPTION
**Pull request by znichollscr**
- [x] #8

### CODE REVIEW

**Review by mikapfl — APPROVED** [review]
Hi,

I think in the context of what's already there, this is fine, an improvement over the status quo.

However, I don't like the function itself. Why have a `format_date` function if it is a super thin wrapper around `strftime`? Maybe I'm very unix-damaged, but for me `date.strftime("%Y")` immediately shows what is happening, while `format_date(date, "yr")` means I have to click through to read the body of the function to know what's happening. So, I'd advocate for deleting the `format_date` function instead unless there is another reason to keep it that I missed.

Cheers,

Mika

**Comment by znichollscr** [comment]
> However, I don't like the function itself. Why have a format_date function if it is a super thin wrapper around strftime? Maybe I'm very unix-damaged, but for me date.strftime("%Y") immediately shows what is happening, while format_date(date, "yr") means I have to click through to read the body of the function to know what's happening. So, I'd advocate for deleting the format_date function instead unless there is another reason to keep it that I missed.

Yep this is a good point. There is further context which is why this makes sense I think:

- the CMIP controlled vocabularies have rules for how the dates should be formatted based on the frequency (which itself follows a controlled vocabulary)
- as a result, I want to abstract away the rules. Basically, I want a function where I can say, given this frequency rule (which could be normal things like "mon" or "yr" but also much weirder things like "3hr", "yrptC", "monC" which don't translate easily or obviously into strftime arguments), format the date. 
- So yep, right now it's super thin but this interface is actually helpful because it will soon grow to actually needing to handle weird edge cases which we will face

**Comment by mikapfl** [comment]
I see, then the function makes sense, definitely.

**Review by lewisjared — APPROVED** [review]

**Comment by lewisjared** [comment]
Mika's question suggests the need to clarify in the docstring that `ds_frequency` confirms with the CMIP6 CV for frequency: https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_frequency.json

**Comment by znichollscr** [comment]
> Mika's question suggests the need to clarify in the docstring that ds_frequency confirms with the CMIP6 CV for frequency: https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_frequency.json

Yes, but it's actually not that CV, but this one https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/input4MIPs_frequency.json

I will speak to Paul about this and then propagate back. I've made #10 as a reminder

**Pull request merged**
